title: International Press journal ICCM Notices author support
description: TeX related material for the manuscript preparation for the 
             International Press journal Notices of the International Congress of Chinese Mathematicians
             (ICCM Notices)
show_downloads: true
theme: jekyll-theme-tactile
